### ISSUE TITLE
"View annotation" feature via annotator_view

### ISSUE THREAD

**Issue by danohuiginn** [edgeryders/openethnographer#15]
Important, since it provides Open Ethnographer with its basic "sidebar style" interface. Should maybe probably result in its own Drupal project.

**Comment by danohuiginn** [comment]
I have some work-in-progress on this at https://github.com/danohuiginn/openethnographer/tree/_sidebar_wip

There are still some technical things to fix on it. But after that, we're going to need to cycle back and look at it from a UI/Design perspective, and figure out what changes we need.

**Comment by danohuiginn** [comment]
more discussion at https://github.com/edgeryders/openethnographer/pull/32

**Comment by tanius** [comment]
The "view annotation" feature with the `annotator_view` plugin got done in the code from #32. However, we decided in the [initial tests](https://edgeryders.eu/en/open-ethnographer/open-ethnographer-sneak-preview-come-and-test) that the sidebar shouldn't contain annotation lists from the text.

Rather tag lists, or the quotation manager, and for that we would use a self-built sidebar rather than puling in all of `annotator_view`. Which will be handled in its own issue.
