### ISSUE TITLE
Node preview shows tags from *all* nodes

### ISSUE THREAD

**Issue by danohuiginn** [edgeryders/openethnographer#16]
The code to show annotations dependent on the current node breaks down when you are previewing new content. It shows all annotations (with correct offsets) for ALL nodes, not just the current one.

**Comment by danohuiginn** [comment]
NB we don't have any reason to use tagging in the preview pane -- so the solution is probably to turn it off rather than making it work

**Comment by tanius** [comment]
Agreed, annotations in the preview pane should be off. Since previews of *new* content do not have a node ID yet, annotations are plain impossible here.

Annotations in previews of changes to *existing* content are technically possible, but if these don't work currently, we better also switch them off. There's no need for them in this context.
